create table if not exists public.qr_notes (
  id bigint generated by default as identity primary key,
  recipient_name text not null check (char_length(trim(recipient_name)) between 1 and 160),
  message text not null check (char_length(trim(message)) between 1 and 5000),
  paper_color text not null default 'parchment' check (paper_color in ('parchment', 'sage', 'blue', 'rose')),
  status text not null default 'published' check (status in ('pending', 'published', 'deleted')),
  manage_token_hash text unique,
  scheduled_publish_at timestamptz,
  schedule_cron_task_uid text,
  audio_path text,
  audio_mime_type text,
  audio_bytes integer check (audio_bytes is null or audio_bytes between 1 and 2000000),
  audio_duration_ms integer check (audio_duration_ms is null or audio_duration_ms between 1 and 30000),
  ambient_light text not null default 'lantern' check (ambient_light in ('lantern', 'moon', 'ember', 'none')),
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists qr_notes_public_feed_idx on public.qr_notes (status, created_at desc, id desc);
create index if not exists qr_notes_recipient_search_idx on public.qr_notes (lower(recipient_name));
create index if not exists qr_notes_schedule_idx on public.qr_notes (schedule_cron_task_uid);

create table if not exists public.qr_note_reports (
  id bigint generated by default as identity primary key,
  note_id bigint not null references public.qr_notes(id) on delete cascade,
  reason text not null check (reason in ('spam', 'harassment', 'private', 'impersonation', 'other')),
  explanation text,
  status text not null default 'open' check (status in ('open', 'reviewed', 'resolved')),
  reporter_key_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists qr_note_reports_status_idx on public.qr_note_reports (status, created_at desc);
create index if not exists qr_note_reports_note_idx on public.qr_note_reports (note_id, status);

create table if not exists public.qr_note_reactions (
  id bigint generated by default as identity primary key,
  note_id bigint not null references public.qr_notes(id) on delete cascade,
  reaction text not null default 'remembered',
  reactor_key_hash text not null,
  created_at timestamptz not null default now(),
  unique (note_id, reaction, reactor_key_hash)
);

create index if not exists qr_note_reactions_note_idx on public.qr_note_reactions (note_id);

alter table public.qr_notes enable row level security;
alter table public.qr_note_reports enable row level security;
alter table public.qr_note_reactions enable row level security;

drop policy if exists "public can read published remembrance notes" on public.qr_notes;
create policy "public can read published remembrance notes"
  on public.qr_notes for select
  to anon, authenticated
  using (
    status = 'published'
    and (scheduled_publish_at is null or scheduled_publish_at <= now())
  );

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'qr-audio',
  'qr-audio',
  false,
  2000000,
  array['audio/webm', 'audio/mp4', 'audio/mpeg', 'audio/ogg']::text[]
)
on conflict (id) do update set
  name = excluded.name,
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
